title: Sid Singaravel # Your name or website title
logo: "/images/Linked In Photo-modified.png?raw=true" # Your photo or logo
github:
  is_user_page: false
  is_project_page: false
description: > # Your bio section
  Graduate Analytics @ Northeastern, MA<br>
  Previously, Data Science @ Fidelity, ZoomRx<br>
  Otherwise - cooks, runs, fantasy football.
  <br><br>
  📧 singaravel dot s at northeastern dot edu  <br>
  <a href="https://www.linkedin.com/in/siddharthans/" target="_blank">LinkedIn</a> | 
  <a href="https://github.com/SiddharthanSingaravel/" target="_blank">GitHub</a> |
  <a href="https://sidsingaravel.substack.com/" target="_blank">Substack</a>
  <br><br>
  📄 View my <a href="pdf/Siddharthan_Resume_Data_Scientist.pdf" target="_blank">résumé</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: G-6TJW42B94P
